import "../globals.css";
import type { Metadata } from "next";
import Header from "../components/Header";
import Banner from "../components/Banner";

export const metadata: Metadata = {
  title: "BlogVerse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Banner />
        {children}
      </body>
    </html>
  );
}
